// Places shown as pins on the travel globe, in the order they appear in the
// card index. `paragraphs[0]` sits beside the first photo; the rest are nested
// between later photos.
export const TRAVEL_PLACES = [
  {
    id: "madrid",
    name: "Madrid",
    country: "Spain",
    tagline: "Where I studied abroad",
    lat: 40.4168,
    lon: -3.7038,
    paragraphs: [
      "Madrid is the city I studied abroad in, and it felt like home almost immediately. There's a Chicago touch to it: locals who were endlessly kind and patient while I fumbled through my Spanish trying to talk to them.",
      "It's the perfect blend of big-city amenities without the big-city feel, and that small-town warmth was exactly what I was looking for in my study abroad experience. My Spanish got a hundred times better here, and you'll still catch me dropping a “vale” in the middle of my sentences, which confuses Spanish speakers back in the States.",
    ],
    photos: [
      { src: "/travel/madrid-1.jpg", alt: "Evening at a Madrid street corner, a green pharmacy cross glowing above the sidewalk" },
      { src: "/travel/madrid-3.jpg", alt: "A laptop and two cups of tea on a marble café table beside an ironwork window" },
      { src: "/travel/madrid-4.jpg", alt: "An ornate domed Madrid building catching sunset light behind a leafy park" },
      { src: "/travel/madrid-6.jpg", alt: "A class sitting on picnic blankets in a Madrid park while an instructor presents" },
      { src: "/travel/madrid-2.jpg", alt: "A narrow Madrid street lined with coral and cream buildings under a blue sky" },
      { src: "/travel/madrid-5.jpg", alt: "The Real Basilica de San Francisco el Grande glowing under an orange evening sky" },
    ],
  },
  {
    id: "dolomites",
    name: "The Dolomites",
    country: "Italy · South Tyrol",
    tagline: "My first real hiking trip",
    lat: 46.6946,
    lon: 12.0856,
    paragraphs: [
      "The Dolomites were my first real hiking trip. I came in nervous, and after a series of trains that almost left me stranded in the middle of nowhere, I arrived to one of the greatest views I've ever seen.",
      "Hiking among the mountains, with little huts along the route to stop at, reminded me of how small we are in the grand scheme of things. I'm already looking to go back.",
    ],
    photos: [
      { src: "/travel/dolomites-1.jpg", alt: "A hotel at the foot of a cloud-wrapped Dolomite peak on a rainy day" },
      { src: "/travel/dolomites-2.jpg", alt: "Namish standing on a rock beside the turquoise water of Lago di Braies" },
      { src: "/travel/dolomites-3.jpg", alt: "Lago di Braies from above, rowboats on blue water beneath forested mountains" },
      { src: "/travel/dolomites-4.jpg", alt: "Hikers and grazing cows on an alpine path with snow-dusted peaks beyond" },
      { src: "/travel/dolomites-5.jpg", alt: "Two log huts on a green hillside below a dark pine forest" },
      { src: "/travel/dolomites-6.jpg", alt: "The jagged Sassolungo massif rising above golden meadows and wooden huts" },
    ],
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    tagline: "Existing in the vibe of the city",
    lat: 52.3676,
    lon: 4.9041,
    paragraphs: [
      "Amsterdam isn't a place you go to check things off a list, and that's exactly what makes it so special. You go to exist in the vibe of the city and take in the culture, the people and the architecture. Café Belgique will always have a special place in my heart, the cold and wind made me feel right at home, and I never got over watching cyclists treat a bike like it was a car. The urban planning is something else. It's one of my favorite places I've been.",
      "My favorite memory is a night at Bar Skek, where I ended up friends with a group of Dutch students. A few pints in, one of them sat me down and asked, “So what's going on with Trump?” That turned into a long conversation about how Europe and the United States see each other. Kind people, immaculate vibe, and I'd go back in a heartbeat.",
    ],
    photos: [
      { src: "/travel/amsterdam-1.jpg", alt: "An Amsterdam canal lined with autumn trees and narrow brick houses under heavy clouds" },
      { src: "/travel/amsterdam-2.jpg", alt: "Namish smiling at a wooden table in a dim café with a tall glass of dark beer" },
      { src: "/travel/amsterdam-3.jpg", alt: "Students playing a live set at a bar: a keyboardist, a guitarist in a fur hat and a singer-guitarist on a small stage under a Hey Student chalkboard" },
      { src: "/travel/amsterdam-4.jpg", alt: "Van Gogh's Almond Blossom in a gilt frame on a pale museum wall" },
      { src: "/travel/amsterdam-5.jpg", alt: "A brick Amsterdam townhouse with an arched black double door, wisteria overhead and bicycles parked out front" },
    ],
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    tagline: "My first solo trip",
    lat: 55.6761,
    lon: 12.5683,
    paragraphs: [
      "Copenhagen was a city I missed out on while studying abroad, but one I always wanted to visit. I had heard so much about the quality of life and the social democracy Denmark is known for, and I knew I wanted to experience it. It was also my first solo trip, right after graduation.",
      "I went for six days all by myself. I made incredible friends at my hostel, learned a lot from other people's experiences, and even took a pastry-making class, which produced the best pastries I've ever had in my entire life.",
      "It's a slow city, one of those places you just want to exist in without doing a lot of touristy things. It's the trip that taught me the importance of sitting with your thoughts.",
    ],
    photos: [
      { src: "/travel/copenhagen-1.jpg", alt: "Colourful townhouses along the Nyhavn canal on a bright blue afternoon" },
      { src: "/travel/copenhagen-2.jpg", alt: "Namish taking a selfie on a cobbled square in front of an equestrian statue" },
      { src: "/travel/copenhagen-3.jpg", alt: "Small boats moored along a Christianshavn canal in front of pastel houses" },
      { src: "/travel/copenhagen-4.jpg", alt: "A tray of custard-filled Danish pastries fresh from the bakery" },
    ],
  },
  {
    id: "chiang-mai",
    name: "Chiang Mai",
    country: "Thailand",
    tagline: "Our favorite stop in Thailand",
    lat: 18.6633,
    lon: 98.6554,
    paragraphs: [
      "After I graduated with my master's, two friends and I set out to explore Thailand and Vietnam together. Chiang Mai was on our list, but we didn't really know much about it, and it ended up being our favorite spot of the entire trip.",
      "We hiked up to a temple at sunrise and watched monks clean up their workspaces and begin their daily meditations. We took cooking classes, met elephants, and had plenty of nights of liquid mischief at local jazz bars.",
      "Chiang Mai embodied true balance in every part of my life. We spent our days eating khao soi and our nights at the jazz bar, and topped it off by meditating at a Buddhist temple on top of a mountain. Those are memories I will never forget.",
    ],
    photos: [
      { src: "/travel/chiang-mai-1.jpg", alt: "A small Thai temple with tiered roofs and red doors lit by late sun beneath tall trees" },
      { src: "/travel/chiang-mai-2.jpg", alt: "A plate of stir-fried flat rice noodles with greens, egg and a lime wedge" },
      { src: "/travel/chiang-mai-3.jpg", alt: "Namish and two friends sitting side by side in a shallow, clear waterfall pool in the jungle" },
      { src: "/travel/chiang-mai-4.jpg", alt: "A thickly painted canvas reading Free Jazz, with three musicians playing horns, hung on a dark wall" },
      { src: "/travel/chiang-mai-5.jpg", alt: "Two bowls of creamy khao soi topped with crispy noodles beside a plate of purple rice" },
      { src: "/travel/chiang-mai-6.jpg", alt: "Two Chang beer bottles cooling in a green bowl under running water" },
    ],
  },
  {
    id: "ha-giang",
    name: "Hà Giang",
    country: "Vietnam",
    tagline: "Glad I didn't cancel",
    lat: 23.1,
    lon: 105.2,
    paragraphs: [
      "I almost canceled this trip three days before it was meant to start because I wasn't sure it was safe, and thank God I went. I stayed at Cheers Hostel and met a ton of new people from all over the world.",
      "Local tour guides took us through their homes, their villages and the mountain scenery. I spent eight hours a day on the back of a motorcycle talking to my guide, and my nights chatting with old and new friends about chasing your dreams, doing what you want, heartbreak, and moving forward. We shared what we'd learned about the countries we came from and what's important to each of us.",
      "These are all parts of a post-grad experience I never want to take for granted, and experiences I'll never forget.",
    ],
    photos: [
      { src: "/travel/ha-giang-1.jpg", alt: "Namish on a wooden lookout beside a Vietnamese flag above a winding mountain road" },
      { src: "/travel/ha-giang-2.jpg", alt: "A rider on a loaded motorbike on a curving road between steep green mountains" },
      { src: "/travel/ha-giang-3.jpg", alt: "Two friends posing under a waterfall with a Vietnamese flag on a pole" },
    ],
  },
  {
    id: "kerala",
    name: "Kerala",
    country: "India",
    tagline: "A week solo in South India",
    lat: 9.5,
    lon: 76.6,
    paragraphs: [
      "Kerala was a week-long solo trip in India. I stayed in hostels the whole time, wandered around Varkala Beach, explored tea plantations in Munnar, and stumbled upon the Biennale festival in Old Kochi.",
      "I learned a lot about South Indian culture, which is different from my own North Indian one. India is as diverse as a continent smushed into a country, and each state brings its own food, culture and mentality with it. The artwork took me away, and so did how beautiful and well maintained the nature is.",
      "What I'll never forget is how eager people were to show off their beautiful country, God's Own Country, as they call it, with their hospitality.",
    ],
    photos: [
      { src: "/travel/kerala-1.jpg", alt: "Rolling Munnar tea plantations beneath a rocky mountain and cloudy sky" },
      { src: "/travel/kerala-2.jpg", alt: "Waves breaking against the base of a palm-topped cliff at Varkala" },
      { src: "/travel/kerala-3.jpg", alt: "A busy paved street in Fort Kochi lined with tiled-roof colonial buildings" },
      { src: "/travel/kerala-4.jpg", alt: "A red dirt lane past a curved blue-and-white guesthouse and palm trees in Varkala" },
      { src: "/travel/kerala-5.jpg", alt: "A checkered-tile terrace looking over forested hills and tea terraces at dusk" },
      { src: "/travel/kerala-6.jpg", alt: "A framed red-toned print of boats and a full moon hung in a dark gallery" },
    ],
  },
  {
    id: "kangra-valley",
    name: "Kangra",
    country: "India · Himachal Pradesh",
    tagline: "My ancestral home",
    lat: 32.1054,
    lon: 76.384,
    paragraphs: [
      "Kangra is my ancestral home. I've grown up going here, and the mountains still never fail to take my breath away. It sits right next to the home of the Dalai Lama.",
      "There's a serenity in small-town life. It's a village where everything closes at 8 p.m. and the new craze of the town is the local gym that just opened. It's astounding to me that this is where my dad grew up while I got to grow up in the United States. It's both a reminder of what could have been and of what I have to be grateful for.",
      "The people here are incessantly kind and always have a smile on their face. They're willing to be friends with anyone, and I hope I carry that attitude throughout my life. One day I'd love to retire here.",
    ],
    photos: [
      { src: "/travel/kangra-valley-1.jpg", alt: "Snow-covered Himalayan peaks glowing pink at sunrise above town rooftops and palm trees, seen from a terrace" },
      { src: "/travel/kangra-valley-3.jpg", alt: "A small local gym with a large Hanuman mural, a supplement shelf and a wooden floor" },
      { src: "/travel/kangra-valley-4.jpg", alt: "A sunlit courtyard with potted flowers, a small tiled shrine and a palm tree, with mountains faintly behind the rooftops" },
      { src: "/travel/kangra-valley-5.jpg", alt: "A golden seated Buddha framed by an ornate jewelled gilt arch inside a temple, a draped yellow cloth in the foreground" },
      { src: "/travel/kangra-valley-6.jpg", alt: "A row of brass prayer wheels engraved with mantras beneath a ledge of potted plants in a sunlit courtyard" },
    ],
  },
  {
    id: "amritsar",
    name: "Amritsar",
    country: "India · Punjab",
    tagline: "Three days of food and prayer",
    lat: 31.62,
    lon: 74.8765,
    paragraphs: [
      "Amritsar was my first solo trip in India after graduating. I spent three days here and did nothing except eat and pray. The serenity I felt at the Golden Temple was irreplaceable, and I listened to kirtan all day.",
      "I was able to get inside the Golden Temple and find a seat right by a window overlooking the English translation of the Punjabi kirtan. I don't fully understand Punjabi, so it felt like a spot that had been reserved just for me.",
    ],
    photos: [
      { src: "/travel/amritsar-1.jpg", alt: "The illuminated Golden Temple reflected in still water beneath a crescent moon" },
      { src: "/travel/amritsar-2.jpg", alt: "A steel plate of stuffed flatbread with chickpea curry, curd and chutney at Brothers Dhaba" },
      { src: "/travel/amritsar-3.jpg", alt: "A steel thali with a stack of flatbread, several curries, chickpeas in curd and an onion salad" },
      { src: "/travel/amritsar-4.jpg", alt: "A customer in a grey waistcoat and flat cap waits at a jalebi stall with a red and yellow striped awning" },
    ],
  },
  {
    id: "chicago",
    name: "Chicago",
    country: "United States",
    tagline: "Home, and everything that happened here",
    lat: 41.8968,
    lon: -87.587,
    paragraphs: [
      "I grew up in Naperville and went to college in Evanston, so Chicagoland has always been home. Chicago is the quintessential Midwestern big city where everyone seems to know each other, and you can always find your community.",
      "Chicago and I have a deep history. It has been in my life since the beginning, and every success and failure, both personal and professional, has taken place in or around this city. I wouldn't trade those experiences for the world.",
    ],
    photos: [
      { src: "/travel/chicago-1.jpg", alt: "The Chicago skyline at dusk across Lake Michigan, the Navy Pier wheel lit in colour" },
      { src: "/travel/chicago-3.jpg", isWide: true, alt: "Namish and two friends on the Evanston lakefront, painted rocks behind them and the Chicago skyline far across the water" },
      { src: "/travel/chicago-4.jpg", alt: "Namish in a purple Northwestern graduation robe and black stole, leaning against a stone pillar and smiling" },
      { src: "/travel/chicago-5.jpg", alt: "Six friends in purple graduation robes posing in front of a lecture hall chalkboard that reads Econ 310-1" },
      { src: "/travel/chicago-2.jpg", alt: "Glass towers on the Chicago lakefront lit up at dusk, seen from a boat on the water" },
      { src: "/travel/chicago-6.jpg", alt: "Namish and two friends in black leather jackets on the steps of the illuminated Baha'i House of Worship at night" },
      { src: "/travel/chicago-7.jpg", alt: "Three friends gathered around a DJ controller and laptop on a rooftop deck at sunset, one wearing headphones" },
    ],
  },
  {
    id: "seattle",
    name: "Seattle",
    country: "United States · Washington",
    tagline: "Spring break, and cherry blossoms by accident",
    lat: 47.6062,
    lon: -122.3321,
    paragraphs: [
      "Seattle was a spring break trip that two friends from Northwestern and I took. It was not well planned at all, but somehow we stumbled upon cherry blossom season right when we were there. It's a city that lends itself to letting whatever happens happen.",
      "The scenery around the city was incredible. It was the first mountain hike I'd ever been on (Poo Poo Point is actually a difficult hike), and it's where I got close to two friends who I still consider very close from my college days.",
      "The tech and indie scenes seem to meld together in a way you wouldn't think is possible. And the cherry blossoms are truly the cherry on top. (Corny, I know.)",
    ],
    photos: [
      { src: "/travel/seattle-1.jpg", alt: "Namish and two friends with their arms around each other beneath a street of blooming cherry trees" },
      { src: "/travel/seattle-2.jpg", alt: "Mount Rainier glowing in golden light above the Seattle skyline" },
      { src: "/travel/seattle-3.jpg", alt: "Namish looking up at a huge moss-covered cherry tree in full bloom on a lawn" },
      { src: "/travel/seattle-4.jpg", alt: "A sidewalk strewn with pink magnolia petals beneath blooming trees" },
    ],
  },
];
